# Configuration Netlify pour Heroes Arena
[build]
  publish = "."
  functions = "netlify/functions"

# Redirections pour les API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Configuration pour le développement local
[dev]
  functions = "netlify/functions"
  port = 8888

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les fichiers statiques
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration pour les modules ES6
[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"